version: '3.8'

services:
  sofa:
    build:
      context: .
      dockerfile: Dockerfile
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - ./data:/root/SOFA/v24.06.00  # Для обмена файлами между хостом и контейнером
      - /tmp/.X11-unix:/tmp/.X11-unix  # Монтирование сокета X11

    environment:
      - DISPLAY=host.docker.internal:0

    command: bash -c "echo $DISPLAY"